-- =============================================================================
-- Movimentações de Conta Corrente (extrato financeiro Omie)
-- Fonte: /financas/mf/ ListarMovimentos (sincronizado por sincronizarMovimentosCC
-- em src/lib/dre-financeiro/omie-api.js). Uma linha por movimento (baixa /
-- lançamento) — codigo_titulo liga com contas_pagar/contas_receber.codigo_lancamento
-- (+ conta_omie) para o cruzamento com títulos.
--
-- APLICAR MANUALMENTE no SQL Editor do Supabase.
-- =============================================================================

create table if not exists public.movimentos_cc (
  id bigint generated by default as identity primary key,

  conta_omie text not null,                      -- 'NOVA' | 'CASTRO' (labelConta)
  codigo_movimento bigint not null default 0,    -- nCodMovCC (0 quando ausente)
  codigo_titulo bigint not null default 0,       -- nCodTitulo (liga com contas_pagar/receber.codigo_lancamento)
  natureza text not null default '',             -- 'P' (saída) | 'R' (entrada)

  origem text,                                   -- cOrigem (ex: conta a pagar, lançamento manual de CC...)
  tipo_documento text,                           -- cTipo
  status text,                                   -- cStatus
  numero_documento text,
  numero_documento_fiscal text,
  numero_parcela text,

  data_emissao date,
  data_vencimento date,
  data_previsao date,
  data_pagamento date,

  valor_documento numeric(14,2) default 0,       -- nValorTitulo
  valor_pago numeric(14,2) default 0,            -- resumo.nValPago (o que circulou de fato)
  valor_liquido numeric(14,2) default 0,         -- resumo.nValLiquido
  valor_aberto numeric(14,2) default 0,          -- resumo.nValAberto
  juros numeric(14,2) default 0,
  multa numeric(14,2) default 0,
  desconto numeric(14,2) default 0,
  liquidado text,                                -- resumo.cLiquidado ('S'/'N')

  codigo_conta_corrente bigint,                  -- nCodCC
  nome_conta_corrente text,                      -- resolvido via ListarContasCorrentes

  codigo_categoria text,
  descricao_categoria text,
  grupo_categoria text,
  codigo_departamento text,
  descricao_departamento text,

  codigo_cliente_fornecedor bigint,              -- nCodCliente
  nome_cliente_fornecedor text,                  -- resolvido via ListarClientesResumido

  raw jsonb,                                     -- payload completo do movimento (detalhes+resumo+categorias+departamentos)
  synced_at timestamptz default now(),

  -- Chave natural do upsert (colunas NOT NULL com default para a unique funcionar
  -- com registros sem nCodMovCC ou sem nCodTitulo).
  unique (conta_omie, natureza, codigo_movimento, codigo_titulo)
);

create index if not exists idx_movcc_conta_dtpag on public.movimentos_cc (conta_omie, data_pagamento);
create index if not exists idx_movcc_titulo on public.movimentos_cc (codigo_titulo);
create index if not exists idx_movcc_conta_corrente on public.movimentos_cc (codigo_conta_corrente);

-- Sem policies: leitura/escrita apenas via service role (rotas /api do portal).
alter table public.movimentos_cc enable row level security;
