-- =====================================================================
-- Nova Tratores — /propostas: campo "Tag/Grupo" por proposta
-- Data: 2026-08-31
--
-- Espelha o sistema de tags das Requisições (tabela requisicao_tags), mas
-- cada proposta guarda UMA tag (FK tag_id em "Formulario"), gerenciável por
-- um modal (criar/editar/excluir nome, cor e grupo). Sem filtro — só exibe.
--
-- GOTCHA do projeto: v_formulario é "SELECT f.*, ..." e o Postgres expande o
-- * na criação. Uma coluna nova em "Formulario" NÃO aparece na view até
-- recriá-la. Por isso recriamos a view aqui (base = propostas-fab-real.sql,
-- a definição vigente) re-expandindo f.* e expondo tag_nome / tag_cor.
--
-- Rodar em transação, ANTES do deploy.
-- =====================================================================

BEGIN;

-- 1) Vocabulário de tags (gerenciado pelo modal, escrito com a chave anon)
CREATE TABLE IF NOT EXISTS proposta_tags (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome  text NOT NULL,
  cor   text,
  grupo text   -- 'categoria' | 'sistema' | 'geral' (organiza as tags no modal)
);

-- Grants iguais aos de requisicao_tags (o ModalTags escreve direto via cliente)
GRANT SELECT, INSERT, UPDATE, DELETE ON proposta_tags TO anon, authenticated;

-- 2) Tag da proposta (SET NULL: excluir tag no modal não quebra propostas)
ALTER TABLE "Formulario"
  ADD COLUMN IF NOT EXISTS tag_id bigint
  REFERENCES proposta_tags(id) ON DELETE SET NULL;

-- 3) Recriar a view expondo tag_nome / tag_cor (base: propostas-fab-real.sql)
DROP VIEW IF EXISTS v_formulario;
CREATE VIEW v_formulario AS
SELECT f.*,
       CASE WHEN f.deleted_at IS NOT NULL THEN 'Lixeira' ELSE f.status END AS status_ui,
       round(extract(epoch from (now() - f.status_desde)) / 86400.0)::int AS dias_na_fase,
       round(extract(epoch from (now() - f.criado_em))   / 86400.0)::int AS dias_total,
       sp.cor_hex, sp.em_aberto, sp.ordem AS status_ordem, sp.probabilidade,
       vend.nome AS vendedor_nome,
       pf.custo AS fabrica_custo,
       pf.id    AS fabrica_pedido_id,      -- null se id_fabrica_ref não aponta p/ pedido real
       t.nome   AS tag_nome,
       t.cor    AS tag_cor
  FROM "Formulario" f
  LEFT JOIN status_proposta sp ON sp.nome = f.status
  LEFT JOIN vendedores vend    ON vend.id = f.vendedor_id
  LEFT JOIN "Proposta_Fabrica" pf
    ON pf.id = nullif(f.id_fabrica_ref, '')::bigint AND pf.deleted_at IS NULL
  LEFT JOIN proposta_tags t    ON t.id = f.tag_id;

COMMIT;

-- Verificação:
--   SELECT tag_id, tag_nome, tag_cor FROM v_formulario LIMIT 5;
