-- Tratorilson pergunta pra equipe quando NÃO SABE lidar com uma situação nova
-- no WhatsApp. A resposta do usuário vira regra na memória dele.
-- RLS ON sem policy (escrita/leitura só pelas rotas com service role).

create table if not exists tratorilson_perguntas (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  contato_nome text,
  contato_telefone text,
  pergunta text not null,
  contexto text,
  status text not null default 'aberta',   -- aberta | respondida | fechada
  resposta text,
  respondido_por text,
  respondido_em timestamptz
);
alter table tratorilson_perguntas enable row level security;

-- Quem recebe o alerta central das perguntas (até 5, escolhidos na página da memória)
create table if not exists tratorilson_notificados (
  id bigint generated by default as identity primary key,
  email text not null unique,
  nome text,
  criado_em timestamptz not null default now()
);
alter table tratorilson_notificados enable row level security;

notify pgrst, 'reload schema';
